# SPDX-License-Identifier: GPL-2.0
VERSION = 6
PATCHLEVEL = 10
SUBLEVEL = 0
EXTRAVERSION = -krypton-generic
NAME = KryptonOS Official Kernel Header Tree

export VERSION PATCHLEVEL SUBLEVEL EXTRAVERSION

CC = gcc
LD = ld
AR = ar

all:
	@echo "KryptonOS Linux 6.10.0-krypton-generic kernel build system ready."
